#!/usr/bin/env bash
# JIT Access Setup Instructions
# Provides instructions for enabling Just-in-Time access for all lab VMs

RG_NAME="lab-complete-rg"

echo "🔒 JIT Access Setup Instructions"
echo "================================"
echo ""
echo "JIT (Just-in-Time) access must be configured through the Azure Portal."
echo "Here's how to enable it for your lab VMs:"
echo ""
echo "📋 Step-by-Step Instructions:"
echo ""
echo "1. 🌐 Go to Azure Portal (portal.azure.com)"
echo "2. 🔍 Search for 'Security Center' or 'Microsoft Defender for Cloud'"
echo "3. 📊 Navigate to 'Just-in-time VM access'"
echo "4. ⚙️  Click 'Configure'"
echo ""
echo "5. 🖥️  For each VM, configure the following:"
echo ""
echo "   📌 Domain Controller (dc):"
echo "   - Port: 3389 (RDP)"
echo "   - Max request time: 8 hours"
echo "   - Source IPs: 0.0.0.0/0 (or your specific IP)"
echo ""
echo "   📌 Windows Client (client):"
echo "   - Port: 3389 (RDP)"
echo "   - Max request time: 8 hours"
echo "   - Source IPs: 0.0.0.0/0 (or your specific IP)"
echo ""
echo "   📌 Linux Client (linux-client):"
echo "   - Port: 22 (SSH)"
echo "   - Max request time: 8 hours"
echo "   - Source IPs: 0.0.0.0/0 (or your specific IP)"
echo ""
echo "   📌 Jumpbox (jumpbox):"
echo "   - Port: 3389 (RDP)"
echo "   - Max request time: 8 hours"
echo "   - Source IPs: 0.0.0.0/0 (or your specific IP)"
echo ""
echo "6. ✅ Save the configuration"
echo ""
echo "🔐 How to use JIT access once configured:"
echo "1. Go to Security Center → Just-in-time VM access"
echo "2. Select the VM you want to access"
echo "3. Click 'Request access' for the port you need"
echo "4. Access will be granted for the configured time"
echo "5. After the time limit, access is automatically revoked"
echo ""
echo "💡 Benefits of JIT access:"
echo "   - Temporarily opens specific ports only when needed"
echo "   - Requires approval for access"
echo "   - Automatically closes ports after time limit"
echo "   - Logs all access attempts for security auditing"
echo "   - Reduces attack surface by keeping ports closed by default"
echo ""
echo "🔗 Direct link to JIT access:"
echo "https://portal.azure.com/#view/Microsoft_Azure_Security/SecurityMenuBlade/~/JustInTime"
